### ISSUE TITLE
Add a meaningful diagram to the "Low Stock Products" tile

### ISSUE THREAD

**Issue by janis-kra** [ADFCommunityDE/AltaUI#14]
This tile currently only shows a picture, but should already represent some meaningful data, e.g. some chart showing the products with the lowest stock or a bar chart showing the amount of ordered products that cannot be delivered because they are not in stock.

Clicking the link should lead to the inventory control page, with the clicked item already shown or selected.

<img width="660" alt="screen shot 2015-10-28 at 12 38 33" src="https://cloud.githubusercontent.com/assets/8240324/10787374/d11c09e8-7d70-11e5-92f9-3b95c4cf7fa0.png">

**Comment by mketeam** [comment]
Maybe create Bar Chart with low stock items. On click start refill process
