### ISSUE TITLE
Also display yellow items in Inventory Control startup page

### ISSUE THREAD

**Issue by janis-kra** [ADFCommunityDE/AltaUI#20]
The inventory control page currently only shows red elements on startup:
<img width="1006" alt="screen shot 2015-11-11 at 12 43 36" src="https://cloud.githubusercontent.com/assets/8240324/11090416/fc3ad206-8871-11e5-8d51-c1120e9d7d58.png">
For presentation purposes, it would be better if the user already sees yellow items (e.g. **increase the stock of at least three elements in the above list**)

**Comment by mketeam** [comment]
Will do a data export on Monday that has yellow and red states. We should use the exported data for presentation purposes
