### ISSUE TITLE
Create Map Dashboard Entry

### ISSUE THREAD

**Issue by mketeam** [ADFCommunityDE/AltaUI#3]
Create an entry point for the dashboard navigation tab. This should contain a thematic map, that shows all customers/stores and shall enable a drill in feature in future,

**Comment by janis-kra** [comment]
Note: In order to fix the issue regarding the height of tooltips, the CSS class _OraDVTDatatipPopup_ must be overwritten

**Comment by janis-kra** [comment]
The feature itself finished, but there are two issues left that must still be solved:
- when navigating via the thematic map, the global navigation state is not updated (i.e. "Dashboard" is still highlighted)
- we need real coordinates for the customer locations (i.e. the database and model must be altered) - I created a separate issue for this

**Comment by janis-kra** [comment]
Implemented in https://github.com/ADFCommunityDE/AltaUI/commit/512aaf72d723e8bfe13021f98368d2488572ece1
