### ISSUE TITLE
Add city locations to the database

### ISSUE THREAD

**Issue by janis-kra** [ADFCommunityDE/AltaUI#5]
In order to correctly display the customers on a map:
1. city locations must be added to the database (MK)
   - at least 5 customers should have correct coordinates, the rest of the coordinates may be set to a negative value (i.e. they would not be displayed on the map)
2. the build scripts should be updated to reflect this change (MK)
3. the business components must be updated accordingly (MK)
4. the thematic map point location layer must use the new coordinates instead of the faked ones (JK)

**Comment by janis-kra** [comment]
You can change the assignee once 1.-3. are finished.

**Comment by mketeam** [comment]
Implementation of Geo_Coordinates done. The realization uses longitude and latitude coordinates, but can be changed easily if this helps for the integration with the map component.

Also added the coordinates to the BC Layer. Also did some refactoring to the package structure to keep it in sync with the other use case. I hope this does not start any trouble

**Comment by janis-kra** [comment]
Implemented in https://github.com/ADFCommunityDE/AltaUI/commit/512aaf72d723e8bfe13021f98368d2488572ece1
